[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:The 'app' shortcut is now deprecated:DeprecationWarning
    ignore:websockets.legacy is deprecated:DeprecationWarning
    ignore:UserImageMessage is deprecated and will be removed:DeprecationWarning
